# Generated by Django 2.1.4 on 2018-12-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('slug', models.SlugField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('latency', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('packet_loss', models.IntegerField(default=0)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.Monitor')),
            ],
        ),
    ]
