# Generated by Django 2.1.4 on 2018-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_auto_20181215_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='slug',
            field=models.SlugField(max_length=15),
        ),
    ]
