# Generated by Django 2.1.4 on 2018-12-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_auto_20181213_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='last_latency',
        ),
    ]
