# Generated by Django 2.1.4 on 2018-12-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_remove_monitor_last_latency'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_latency',
            field=models.IntegerField(default=0),
        ),
    ]
