# Generated by Django 2.1.4 on 2018-12-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0007_monitor_last_packet_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='last_latency',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='last_packet_loss',
        ),
    ]
