# Generated by Django 2.1.4 on 2018-12-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0008_auto_20181213_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_latency',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monitor',
            name='last_packet_loss',
            field=models.IntegerField(default=0),
        ),
    ]
