# Generated by Django 2.1.4 on 2018-12-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0009_auto_20181213_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='last_latency',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='last_packet_loss',
        ),
        migrations.AddField(
            model_name='result',
            name='latency',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='result',
            name='packet_loss',
            field=models.IntegerField(default=0),
        ),
    ]
